# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: UI Kit Actions

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Dependencies ğŸ”§
        run: npm ci

      - name: Lint ğŸ§¹
        run: npm run lint

      - name: Build ğŸ”¨
        run: npm run dist

      - name: Unit Tests ğŸ§ª
        run: npm test

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run test:integration

      - name: Semantic Release â¬†ï¸
        if: github.ref == 'refs/heads/master'
        uses: cycjimmy/semantic-release-action@v2.6.0
        with:
          semantic_version: 18
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build Storybook and Deploy ğŸš€
        if: github.ref == 'refs/heads/master'
        run: |
          npm run build:storybook
          npm run deploy:storybook -- --ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
