name: UI Kit Code Checks
on:
  pull_request:
  push:
    branches: [main]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install Dependencies ğŸ”§
        run: npm install
      - name: Lint ğŸ§¹
        run: npm run lint
      - name: Build ğŸ”¨
        run: npm run dist
      - name: Unit Tests ğŸ§ª
        run: npm test
      - name: Semantic Release â¬†ï¸
        if: github.ref == 'refs/heads/main'
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build Storybook and Deploy ğŸš€
        if: github.ref == 'refs/heads/main'
        run: |
          npm run build:storybook
          npm run deploy:storybook -- --ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
