name: Storybook Tests
on: push
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".node-version"
          cache: "npm"
      - name: Install Dependencies ðŸ”§
        run: npm ci
      - name: Install Playwright ðŸŽ­
        run: npx playwright install --with-deps
      - name: Run Storybook Tests ðŸ“š
        run: npm run build:storybook --quiet
      - name: Serve Storybook and Run Tests ðŸ“–
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook_static --port 6006 --silent" \
            "npx wait-on http://127.0.0.1:6006 && npm run test-storybook"
